# Generated by Django 4.1.4 on 2022-12-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
