# Generated by Django 4.1.4 on 2022-12-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1995-03-08'),
            preserve_default=False,
        ),
    ]
